# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-31 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='oreder',
            new_name='order',
        ),
    ]
